#!/usr/bin/env python3
"""
깨끗한 로컬 가상환경을 사용해 THIRD_PARTY_LICENSES 생성 (Windows 전용)
"""

import subprocess
import sys
from pathlib import Path

# 경로 설정
PROJECT_ROOT = Path(__file__).resolve().parents[1]
VENV_DIR = PROJECT_ROOT / ".licenses_venv"
VENV_PYTHON = VENV_DIR / "Scripts" / "python.exe"
VENV_PIP = VENV_DIR / "Scripts" / "pip.exe"

LICENSES_FILE = PROJECT_ROOT / "THIRD_PARTY_LICENSES"

HEADER = """THIRD-PARTY SOFTWARE LICENSE NOTICES

This file is automatically generated.
It lists the licenses of third-party Python packages used by this project.

------------------------------------------------------------
"""


def stream(cmd, cwd=PROJECT_ROOT):
    """
    명령을 실행하고 stdout/stderr를 실시간으로 출력한다.
    실패 시 예외를 발생시킨다.
    """
    process = subprocess.Popen(
        cmd,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        shell=False,
    )

    output_lines = []

    for line in process.stdout:
        print(line, end="")
        output_lines.append(line)

    return_code = process.wait()
    if return_code != 0:
        raise subprocess.CalledProcessError(return_code, cmd)

    return "".join(output_lines)


def main():
    LICENSES_FILE.parent.mkdir(parents=True, exist_ok=True)

    # 1. 가상환경 생성
    if not VENV_PYTHON.exists():
        print("가상환경 생성 중...")
        stream([sys.executable, "-m", "venv", str(VENV_DIR)])

    # 2. pip 업그레이드
    print("pip 업그레이드 중...")
    stream([str(VENV_PYTHON), "-m", "pip", "install", "--upgrade", "pip"])

    # 3. 프로젝트 editable 설치
    print("프로젝트 editable 설치 중...")
    stream([str(VENV_PIP), "install", "-e", "."], cwd=PROJECT_ROOT)

    # 4. pip-licenses 설치
    print("pip-licenses 설치 중...")
    stream([str(VENV_PIP), "install", "pip-licenses"])

    # 5. 라이선스 생성
    print("THIRD_PARTY_LICENSES 생성 중...")
    licenses_output = stream(
        [
            str(VENV_PYTHON),
            "-m",
            "pip_licenses",
            "--format=plain",
            "--with-authors",
            "--with-license-file",
            "--no-version",
        ],
        cwd=PROJECT_ROOT,
    )

    LICENSES_FILE.write_text(HEADER + licenses_output, encoding="utf-8")
    print(f"생성 완료: {LICENSES_FILE}")


if __name__ == "__main__":
    main()
